packages:
  - 'apps/*'
  - 'packages/*'

strictDepBuilds: true

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.8'
  - '@tanstack/react-query@5.102.8'
