// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/bao-cao-don-hang-doanh-thu" | "/bao-cao-ton-kho" | "/bao-cao-truy-xuat" | "/cau-hinh" | "/chung-nhan" | "/dang-nhap" | "/danh-gia" | "/danh-muc-san-pham" | "/don-hang" | "/flash-sale" | "/giao-dich-ton-kho" | "/hoa-don" | "/hoa-hong" | "/khach-hang" | "/khieu-nai" | "/kho" | "/khuyen-mai" | "/kiem-dinh-chat-luong" | "/lo-san-pham" | "/mua-vu" | "/nha-cung-cap" | "/nhan-vien" | "/nhat-ky-canh-tac" | "/nhat-ky-kiem-toan" | "/noi-dung-trang-chu" | "/phan-quyen" | "/phieu-kho" | "/san-pham" | "/su-kien-truy-xuat" | "/tai-chinh" | "/thong-bao" | "/thu-hoach" | "/ton-kho" | "/trang-trai"
type AppRouteHandlerRoutes = "/api/anh-san-pham"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/anh-san-pham": {}
  "/bao-cao-don-hang-doanh-thu": {}
  "/bao-cao-ton-kho": {}
  "/bao-cao-truy-xuat": {}
  "/cau-hinh": {}
  "/chung-nhan": {}
  "/dang-nhap": {}
  "/danh-gia": {}
  "/danh-muc-san-pham": {}
  "/don-hang": {}
  "/flash-sale": {}
  "/giao-dich-ton-kho": {}
  "/hoa-don": {}
  "/hoa-hong": {}
  "/khach-hang": {}
  "/khieu-nai": {}
  "/kho": {}
  "/khuyen-mai": {}
  "/kiem-dinh-chat-luong": {}
  "/lo-san-pham": {}
  "/mua-vu": {}
  "/nha-cung-cap": {}
  "/nhan-vien": {}
  "/nhat-ky-canh-tac": {}
  "/nhat-ky-kiem-toan": {}
  "/noi-dung-trang-chu": {}
  "/phan-quyen": {}
  "/phieu-kho": {}
  "/san-pham": {}
  "/su-kien-truy-xuat": {}
  "/tai-chinh": {}
  "/thong-bao": {}
  "/thu-hoach": {}
  "/ton-kho": {}
  "/trang-trai": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
