// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/bao-cao-don-hang-doanh-thu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bao-cao-don-hang-doanh-thu">> = Specific
  const handler = {} as typeof import("../../src/app/bao-cao-don-hang-doanh-thu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bao-cao-ton-kho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bao-cao-ton-kho">> = Specific
  const handler = {} as typeof import("../../src/app/bao-cao-ton-kho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bao-cao-truy-xuat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bao-cao-truy-xuat">> = Specific
  const handler = {} as typeof import("../../src/app/bao-cao-truy-xuat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cau-hinh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cau-hinh">> = Specific
  const handler = {} as typeof import("../../src/app/cau-hinh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chung-nhan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chung-nhan">> = Specific
  const handler = {} as typeof import("../../src/app/chung-nhan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dang-nhap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dang-nhap">> = Specific
  const handler = {} as typeof import("../../src/app/dang-nhap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/danh-gia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/danh-gia">> = Specific
  const handler = {} as typeof import("../../src/app/danh-gia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/danh-muc-san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/danh-muc-san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/danh-muc-san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/don-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/don-hang">> = Specific
  const handler = {} as typeof import("../../src/app/don-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flash-sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flash-sale">> = Specific
  const handler = {} as typeof import("../../src/app/flash-sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/giao-dich-ton-kho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/giao-dich-ton-kho">> = Specific
  const handler = {} as typeof import("../../src/app/giao-dich-ton-kho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hoa-don/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hoa-don">> = Specific
  const handler = {} as typeof import("../../src/app/hoa-don/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hoa-hong/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hoa-hong">> = Specific
  const handler = {} as typeof import("../../src/app/hoa-hong/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khach-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khach-hang">> = Specific
  const handler = {} as typeof import("../../src/app/khach-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khieu-nai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khieu-nai">> = Specific
  const handler = {} as typeof import("../../src/app/khieu-nai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kho">> = Specific
  const handler = {} as typeof import("../../src/app/kho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khuyen-mai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khuyen-mai">> = Specific
  const handler = {} as typeof import("../../src/app/khuyen-mai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kiem-dinh-chat-luong/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kiem-dinh-chat-luong">> = Specific
  const handler = {} as typeof import("../../src/app/kiem-dinh-chat-luong/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lo-san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lo-san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/lo-san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mua-vu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mua-vu">> = Specific
  const handler = {} as typeof import("../../src/app/mua-vu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nha-cung-cap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nha-cung-cap">> = Specific
  const handler = {} as typeof import("../../src/app/nha-cung-cap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nhan-vien/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nhan-vien">> = Specific
  const handler = {} as typeof import("../../src/app/nhan-vien/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nhat-ky-canh-tac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nhat-ky-canh-tac">> = Specific
  const handler = {} as typeof import("../../src/app/nhat-ky-canh-tac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nhat-ky-kiem-toan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nhat-ky-kiem-toan">> = Specific
  const handler = {} as typeof import("../../src/app/nhat-ky-kiem-toan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/noi-dung-trang-chu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/noi-dung-trang-chu">> = Specific
  const handler = {} as typeof import("../../src/app/noi-dung-trang-chu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/phan-quyen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phan-quyen">> = Specific
  const handler = {} as typeof import("../../src/app/phan-quyen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/phieu-kho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phieu-kho">> = Specific
  const handler = {} as typeof import("../../src/app/phieu-kho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/su-kien-truy-xuat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/su-kien-truy-xuat">> = Specific
  const handler = {} as typeof import("../../src/app/su-kien-truy-xuat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-chinh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-chinh">> = Specific
  const handler = {} as typeof import("../../src/app/tai-chinh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thong-bao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thong-bao">> = Specific
  const handler = {} as typeof import("../../src/app/thong-bao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thu-hoach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thu-hoach">> = Specific
  const handler = {} as typeof import("../../src/app/thu-hoach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ton-kho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ton-kho">> = Specific
  const handler = {} as typeof import("../../src/app/ton-kho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trang-trai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trang-trai">> = Specific
  const handler = {} as typeof import("../../src/app/trang-trai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/anh-san-pham/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anh-san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/api/anh-san-pham/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
