// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/chinh-sach-bao-mat" | "/dang-ky" | "/dang-nhap" | "/dat-lai-mat-khau" | "/diem-thuong" | "/dieu-khoan" | "/don-hang" | "/don-hang/[id]" | "/gio-hang" | "/goi-y" | "/khieu-nai" | "/khieu-nai/[id]" | "/khieu-nai/tao" | "/khuyen-mai" | "/kien-thuc" | "/quen-mat-khau" | "/san-pham" | "/san-pham/[id]" | "/tai-khoan" | "/tai-khoan/dia-chi" | "/tai-khoan/doi-mat-khau" | "/tai-khoan/ho-so" | "/thanh-toan" | "/thanh-toan/ket-qua" | "/theo-doi" | "/tin-tuc" | "/trang-trai" | "/trang-trai/[id]" | "/truy-xuat" | "/yeu-thich"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/chinh-sach-bao-mat": {}
  "/dang-ky": {}
  "/dang-nhap": {}
  "/dat-lai-mat-khau": {}
  "/diem-thuong": {}
  "/dieu-khoan": {}
  "/don-hang": {}
  "/don-hang/[id]": { "id": string; }
  "/gio-hang": {}
  "/goi-y": {}
  "/khieu-nai": {}
  "/khieu-nai/[id]": { "id": string; }
  "/khieu-nai/tao": {}
  "/khuyen-mai": {}
  "/kien-thuc": {}
  "/quen-mat-khau": {}
  "/san-pham": {}
  "/san-pham/[id]": { "id": string; }
  "/tai-khoan": {}
  "/tai-khoan/dia-chi": {}
  "/tai-khoan/doi-mat-khau": {}
  "/tai-khoan/ho-so": {}
  "/thanh-toan": {}
  "/thanh-toan/ket-qua": {}
  "/theo-doi": {}
  "/tin-tuc": {}
  "/trang-trai": {}
  "/trang-trai/[id]": { "id": string; }
  "/truy-xuat": {}
  "/yeu-thich": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
