// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/chinh-sach-bao-mat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chinh-sach-bao-mat">> = Specific
  const handler = {} as typeof import("../../src/app/chinh-sach-bao-mat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dang-ky/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dang-ky">> = Specific
  const handler = {} as typeof import("../../src/app/dang-ky/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dang-nhap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dang-nhap">> = Specific
  const handler = {} as typeof import("../../src/app/dang-nhap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dat-lai-mat-khau/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dat-lai-mat-khau">> = Specific
  const handler = {} as typeof import("../../src/app/dat-lai-mat-khau/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/diem-thuong/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diem-thuong">> = Specific
  const handler = {} as typeof import("../../src/app/diem-thuong/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dieu-khoan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dieu-khoan">> = Specific
  const handler = {} as typeof import("../../src/app/dieu-khoan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/don-hang/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/don-hang/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/don-hang/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/don-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/don-hang">> = Specific
  const handler = {} as typeof import("../../src/app/don-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gio-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gio-hang">> = Specific
  const handler = {} as typeof import("../../src/app/gio-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/goi-y/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goi-y">> = Specific
  const handler = {} as typeof import("../../src/app/goi-y/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khieu-nai/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khieu-nai/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/khieu-nai/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khieu-nai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khieu-nai">> = Specific
  const handler = {} as typeof import("../../src/app/khieu-nai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khieu-nai/tao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khieu-nai/tao">> = Specific
  const handler = {} as typeof import("../../src/app/khieu-nai/tao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/khuyen-mai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/khuyen-mai">> = Specific
  const handler = {} as typeof import("../../src/app/khuyen-mai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kien-thuc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kien-thuc">> = Specific
  const handler = {} as typeof import("../../src/app/kien-thuc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quen-mat-khau/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quen-mat-khau">> = Specific
  const handler = {} as typeof import("../../src/app/quen-mat-khau/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/san-pham/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/san-pham/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-khoan/dia-chi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan/dia-chi">> = Specific
  const handler = {} as typeof import("../../src/app/tai-khoan/dia-chi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-khoan/doi-mat-khau/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan/doi-mat-khau">> = Specific
  const handler = {} as typeof import("../../src/app/tai-khoan/doi-mat-khau/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-khoan/ho-so/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan/ho-so">> = Specific
  const handler = {} as typeof import("../../src/app/tai-khoan/ho-so/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-khoan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan">> = Specific
  const handler = {} as typeof import("../../src/app/tai-khoan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tai-khoan/voucher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan/voucher">> = Specific
  const handler = {} as typeof import("../../src/app/tai-khoan/voucher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thanh-toan/ket-qua/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thanh-toan/ket-qua">> = Specific
  const handler = {} as typeof import("../../src/app/thanh-toan/ket-qua/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thanh-toan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thanh-toan">> = Specific
  const handler = {} as typeof import("../../src/app/thanh-toan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/theo-doi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/theo-doi">> = Specific
  const handler = {} as typeof import("../../src/app/theo-doi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tin-tuc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tin-tuc">> = Specific
  const handler = {} as typeof import("../../src/app/tin-tuc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trang-trai/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trang-trai/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/trang-trai/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trang-trai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trang-trai">> = Specific
  const handler = {} as typeof import("../../src/app/trang-trai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/truy-xuat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/truy-xuat">> = Specific
  const handler = {} as typeof import("../../src/app/truy-xuat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yeu-thich/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yeu-thich">> = Specific
  const handler = {} as typeof import("../../src/app/yeu-thich/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
