/**
 * Homepage data & local image mappings for AgriMarket Mobile.
 * Synchronized with customer-web to ensure 1:1 brand, content & visual consistency.
 */

export const HERO_BANNERS = [
  {
    id: 'hero-1',
    title: 'Từ trang trại đến bàn ăn',
    subtitle: 'Nguồn gốc minh bạch - Thực phẩm an toàn cho gia đình Việt',
    tag: 'MINH BẠCH',
    image: require('../../assets/images/web/banners/hero-01-nguon-goc-minh-bach.png'),
    category: 'tat-ca',
  },
  {
    id: 'hero-2',
    title: 'Rau củ thu hoạch trong ngày',
    subtitle: 'Tươi xanh chuẩn VietGAP từ các trang trại uy tín',
    tag: 'TƯƠI NGON',
    image: require('../../assets/images/web/banners/hero-02-rau-cu-thu-hoach-trong-ngay.png'),
    category: 'rau-cu',
  },
  {
    id: 'hero-3',
    title: 'Trái cây ngọt lành tự nhiên',
    subtitle: 'Chín cây, đậm vị ngọt lành từ mọi miền đất nước',
    tag: 'THEO MÙA',
    image: require('../../assets/images/web/banners/hero-03-trai-cay-ngot-lanh-tu-nhien.png'),
    category: 'trai-cay',
  },
  {
    id: 'hero-4',
    title: 'Thịt, trứng, thủy sản tươi sạch',
    subtitle: 'Kiểm định nghiêm ngặt, an toàn cho bữa ăn gia đình',
    tag: 'AN TOÀN',
    image: require('../../assets/images/web/banners/hero-04-thit-trung-thuy-san-tuoi-sach.png'),
    category: 'thit-trung',
  },
  {
    id: 'hero-5',
    title: 'Đặc sản vùng miền Việt Nam',
    subtitle: 'Hương vị truyền thống chính gốc từ từng địa phương',
    tag: 'ĐẶC SẢN',
    image: require('../../assets/images/web/banners/hero-05-dac-san-vung-mien.png'),
    category: 'dac-san',
  },
  {
    id: 'hero-6',
    title: 'Combo ưu đãi tiết kiệm',
    subtitle: 'Đủ đầy dinh dưỡng trọn tuần cho cả gia đình',
    tag: 'TIẾT KIỆM',
    image: require('../../assets/images/web/banners/hero-06-combo-uu-dai.png'),
    category: 'combo',
  },
] as const;

export const PROMO_CARDS = [
  {
    id: 'promo-1',
    title: 'Rau củ tươi mỗi ngày',
    badge: 'Giảm đến 30%',
    image: require('../../assets/images/web/hero/promo-rau-cu-tuoi.jpg'),
    category: 'rau-cu',
  },
  {
    id: 'promo-2',
    title: 'Trái cây theo mùa',
    badge: 'Ngọt lành tự nhiên',
    image: require('../../assets/images/web/hero/promo-trai-cay-theo-mua.jpg'),
    category: 'trai-cay',
  },
] as const;

export const TRUST_BADGES = [
  {
    // Web: IconQrcode -> mobile qr-code-outline
    icon: 'qr-code-outline' as const,
    title: 'Truy xuất nguồn gốc',
    subtitle: 'Rõ ràng, minh bạch',
  },
  {
    // Web: IconBuildingStore -> storefront-outline
    icon: 'storefront-outline' as const,
    title: 'Trang trại minh bạch',
    subtitle: 'Kết nối trực tiếp',
  },
  {
    // Web: IconShieldCheck -> shield-checkmark-outline
    icon: 'shield-checkmark-outline' as const,
    title: 'Sản phẩm an toàn',
    subtitle: 'Đạt chuẩn VietGAP',
  },
  {
    // Web: IconHeart ("Vì sức khỏe cộng đồng") -> heart-outline
    // Trước đây dùng leaf-outline + title cụt "Vì sức khỏe" gây lệch web.
    icon: 'heart-outline' as const,
    title: 'Vì sức khỏe cộng đồng',
    subtitle: 'Nông nghiệp bền vững',
  },
] as const;

export const QUICK_CATEGORIES = [
  {
    slug: 'rau-cu',
    label: 'Rau củ',
    image: require('../../assets/images/web/categories/quick-rau-cu.png'),
    icon: 'leaf-outline' as const,
    bg: '#ECFDF5',
    color: '#059669',
  },
  {
    slug: 'trai-cay',
    label: 'Trái cây',
    image: require('../../assets/images/web/categories/quick-trai-cay.png'),
    icon: 'nutrition-outline' as const,
    bg: '#FFF7ED',
    color: '#EA580C',
  },
  {
    slug: 'gao-ngu-coc',
    label: 'Gạo, ngũ cốc',
    image: require('../../assets/images/web/categories/quick-gao-ngu-coc.png'),
    icon: 'basket-outline' as const,
    bg: '#FEFCE8',
    color: '#CA8A04',
  },
  {
    slug: 'thit-trung',
    label: 'Thịt, trứng',
    image: require('../../assets/images/web/categories/quick-thit-trung.png'),
    icon: 'egg-outline' as const,
    bg: '#FEF2F2',
    color: '#DC2626',
  },
  {
    slug: 'thuy-san',
    label: 'Thủy sản',
    image: require('../../assets/images/web/categories/quick-thuy-san.png'),
    icon: 'water-outline' as const,
    bg: '#ECFEFF',
    color: '#0891B2',
  },
  {
    slug: 'do-kho-gia-vi',
    label: 'Đồ khô, gia vị',
    image: require('../../assets/images/web/categories/quick-do-kho-gia-vi.png'),
    icon: 'restaurant-outline' as const,
    bg: '#FFF7ED',
    color: '#C2410C',
  },
  {
    slug: 'dac-san',
    label: 'Đặc sản vùng miền',
    image: require('../../assets/images/web/categories/quick-dac-san.png'),
    icon: 'location-outline' as const,
    bg: '#F5F3FF',
    color: '#7C3AED',
  },
  {
    slug: 'organic',
    label: 'Organic',
    image: require('../../assets/images/web/categories/quick-organic.png'),
    icon: 'checkmark-circle-outline' as const,
    bg: '#ECFDF5',
    color: '#16A34A',
  },
  {
    slug: 'vietgap',
    label: 'VietGAP',
    image: require('../../assets/images/web/categories/quick-vietgap.png'),
    icon: 'shield-checkmark-outline' as const,
    bg: '#E0F2FE',
    color: '#0284C7',
  },
  {
    slug: 'che-bien',
    label: 'Chế biến',
    image: require('../../assets/images/web/categories/quick-che-bien.png'),
    icon: 'cube-outline' as const,
    bg: '#F3F4F6',
    color: '#4B5563',
  },
  {
    slug: 'qua-tang',
    label: 'Quà tặng',
    image: require('../../assets/images/web/categories/quick-qua-tang.png'),
    icon: 'gift-outline' as const,
    bg: '#FDF2F8',
    color: '#DB2777',
  },
  {
    slug: 'combo',
    label: 'Combo ưu đãi',
    image: require('../../assets/images/web/categories/quick-combo.png'),
    icon: 'bag-handle-outline' as const,
    bg: '#EFF6FF',
    color: '#2563EB',
  },
] as const;

export const FLASH_SALE_ITEMS = [
  {
    id: 'fs-1',
    ten: 'Cà chua bi',
    trangTraiTen: 'Trang trại An Phú',
    diaChi: 'Lâm Đồng',
    gia: 32000,
    giaCu: 40000,
    giam: '-20%',
    donVi: '500g',
    image: require('../../assets/images/web/products/flash-ca-chua-bi.jpg'),
    badge: 'VietGAP',
  },
  {
    id: 'fs-2',
    ten: 'Rau xà lách thủy canh',
    trangTraiTen: 'Trang trại Minh Bạch',
    diaChi: 'Hà Nội',
    gia: 25000,
    giaCu: 30000,
    giam: '-15%',
    donVi: '300g',
    image: require('../../assets/images/web/products/flash-xa-lach-thuy-canh.jpg'),
    badge: 'Organic',
  },
  {
    id: 'fs-3',
    ten: 'Cam sành',
    trangTraiTen: 'Đặc sản Hà Giang',
    diaChi: 'Hà Giang',
    gia: 28000,
    giaCu: 37000,
    giam: '-25%',
    donVi: 'kg',
    image: require('../../assets/images/web/products/flash-cam-sanh.jpg'),
    badge: 'Đặc sản',
  },
  {
    id: 'fs-4',
    ten: 'Trứng gà ta',
    trangTraiTen: 'Trang trại Sông Hồng',
    diaChi: 'Hà Nội',
    gia: 35000,
    giaCu: 44000,
    giam: '-20%',
    donVi: 'vỉ 10 quả',
    image: require('../../assets/images/web/products/flash-trung-ga-ta.jpg'),
    badge: 'VietGAP',
  },
  {
    id: 'fs-5',
    ten: 'Thịt bò sạch',
    trangTraiTen: 'Trang trại Minh Bạch',
    diaChi: 'Hà Nội',
    gia: 150000,
    giaCu: 180000,
    giam: '-15%',
    donVi: '500g',
    image: require('../../assets/images/web/products/flash-thit-bo-sach.jpg'),
    badge: 'Sạch tươi',
  },
] as const;

export const FEATURED_CATEGORIES_TABS = [
  { id: 'tat-ca', label: 'Tất cả' },
  { id: 'rau-cu', label: 'Rau củ' },
  { id: 'trai-cay', label: 'Trái cây' },
  { id: 'thit-trung', label: 'Thịt, trứng' },
  { id: 'thuy-san', label: 'Thủy sản' },
  { id: 'dac-san', label: 'Đặc sản' },
  { id: 'organic', label: 'Organic' },
  { id: 'vietgap', label: 'VietGAP' },
] as const;

export const FEATURED_PRODUCTS_FALLBACK = [
  {
    id: 'fp-1',
    ten: 'Súp lơ xanh',
    trangTraiTen: 'Trang trại Minh Bạch',
    diaChi: 'Hà Nội',
    gia: 28000,
    donVi: '500g',
    badge: 'VietGAP',
    category: 'rau-cu',
    image: require('../../assets/images/web/products/suploxanh.jpg'),
  },
  {
    id: 'fp-2',
    ten: 'Dâu tây Đà Lạt',
    trangTraiTen: 'Trang trại An Phú',
    diaChi: 'Lâm Đồng',
    gia: 85000,
    donVi: 'hộp 350g',
    badge: 'Organic',
    category: 'trai-cay',
    image: require('../../assets/images/web/products/dautaydalat.jpg'),
  },
  {
    id: 'fp-3',
    ten: 'Gạo ST25 chuẩn ngon',
    trangTraiTen: 'Trang trại Sông Hồng',
    diaChi: 'Hà Nội',
    gia: 120000,
    donVi: 'túi 5kg',
    badge: 'Đặc sản',
    category: 'dac-san',
    image: require('../../assets/images/web/products/gao.jpg'),
  },
  {
    id: 'fp-4',
    ten: 'Tôm thẻ tươi',
    trangTraiTen: 'Trang trại Minh Bạch',
    diaChi: 'Hà Nội',
    gia: 180000,
    donVi: 'kg',
    badge: 'Tươi sống',
    category: 'thuy-san',
    image: require('../../assets/images/web/products/tom.jpg'),
  },
  {
    id: 'fp-5',
    ten: 'Bơ sáp 034',
    trangTraiTen: 'Trang trại An Phú',
    diaChi: 'Lâm Đồng',
    gia: 45000,
    donVi: 'kg',
    badge: 'VietGAP',
    category: 'trai-cay',
    image: require('../../assets/images/web/products/bo.jpg'),
  },
  {
    id: 'fp-6',
    ten: 'Cà rốt hữu cơ',
    trangTraiTen: 'Trang trại Sông Hồng',
    diaChi: 'Hà Nội',
    gia: 25000,
    donVi: '500g',
    badge: 'Organic',
    category: 'rau-cu',
    image: require('../../assets/images/web/products/carot.jpg'),
  },
  {
    id: 'fp-7',
    ten: 'Chuối già Nam Mỹ',
    trangTraiTen: 'Trang trại An Phú',
    diaChi: 'Lâm Đồng',
    gia: 28000,
    donVi: 'nải 1.2kg',
    badge: 'VietGAP',
    category: 'trai-cay',
    image: require('../../assets/images/web/products/chuoi.jpg'),
  },
  {
    id: 'fp-8',
    ten: 'Nấm hương tươi',
    trangTraiTen: 'Trang trại Minh Bạch',
    diaChi: 'Hà Nội',
    gia: 60000,
    donVi: 'hộp 250g',
    badge: 'Nấm sạch',
    category: 'rau-cu',
    image: require('../../assets/images/web/products/nauhuong.jpg'),
  },
] as const;

export const FEATURED_FARMS = [
  {
    id: 'farm-1',
    ten: 'Trang trại canh tác nông sản Hà Nội',
    diaChi: 'Đông Anh, Hà Nội',
    sao: 4.8,
    soDanhGia: 124,
    sanPhamChinh: 'Rau hữu cơ, củ quả sạch',
    chungNhan: 'VietGAP & Organic',
    image: require('../../assets/images/web/farms/trang-trai-minh-bach-ha-noi.jpg'),
  },
  {
    id: 'farm-2',
    ten: 'Trang trại rau công nghệ cao Đà Lạt',
    diaChi: 'Đức Trọng, Lâm Đồng',
    sao: 4.7,
    soDanhGia: 98,
    sanPhamChinh: 'Dâu tây, ớt chuông, cà chua bi',
    chungNhan: 'Công nghệ cao VietGAP',
    image: require('../../assets/images/web/farms/trang-trai-an-phu-lam-dong.jpg'),
  },
  {
    id: 'farm-3',
    ten: 'Vùng trồng rau xanh Sông Hồng',
    diaChi: 'Gia Lâm, Hà Nội',
    sao: 4.8,
    soDanhGia: 102,
    sanPhamChinh: 'Rau ăn lá, rau thủy canh',
    chungNhan: 'Chuẩn an toàn ATTP',
    image: require('../../assets/images/web/farms/trang-trai-song-hong-ha-noi.jpg'),
  },
] as const;

export const KNOWLEDGE_TABS = [
  { id: 'tat-ca', label: 'Tất cả' },
  { id: 'ky-thuat', label: 'Kỹ thuật' },
  { id: 'dinh-duong', label: 'Dinh dưỡng' },
  // Khớp web: tab `meo-chon` (Mẹo chọn mua). Trước đây mobile dùng `meo-hay`
  // khiến filter lệch web.
  { id: 'meo-chon', label: 'Mẹo chọn mua' },
  { id: 'tin-tuc', label: 'Tin tức' },
] as const;

export const KNOWLEDGE_ARTICLES = [
  {
    id: 'art-1',
    tag: 'Mẹo hay',
    tab: 'meo-chon',
    title: 'Cách chọn rau củ sạch, tươi ngon mỗi ngày',
    moTa: 'Bí quyết nhận biết rau củ an toàn, tươi ngon và giàu dinh dưỡng cho bữa cơm gia đình.',
    date: '12 Th4, 2024',
    views: '2.4K',
    image: require('../../assets/images/web/articles/article-cach-chon-rau-cu-sach.png'),
  },
  {
    id: 'art-2',
    tag: 'Bảo quản',
    tab: 'meo-chon',
    title: 'Mẹo bảo quản trái cây luôn tươi ngon tại nhà',
    moTa: 'Những cách đơn giản giúp trái cây luôn tươi ngon, giữ trọn vẹn vitamin và hương vị.',
    date: '08 Th4, 2024',
    views: '1.8K',
    image: require('../../assets/images/web/articles/article-bao-quan-trai-cay.webp'),
  },
  {
    id: 'art-3',
    tag: 'VietGAP',
    tab: 'ky-thuat',
    title: 'VietGAP là gì? Vì sao người tiêu dùng nên lựa chọn?',
    moTa: 'Tìm hiểu tiêu chuẩn VietGAP và lợi ích thiết thực đối với sức khỏe của cả gia đình.',
    date: '05 Th4, 2024',
    views: '3.1K',
    image: require('../../assets/images/web/articles/article-vietgap-la-gi.png'),
  },
  {
    id: 'art-4',
    tag: 'Theo mùa',
    tab: 'dinh-duong',
    title: 'Nông sản theo mùa có gì đặc biệt tốt cho sức khỏe?',
    moTa: 'Khám phá lợi ích của việc ăn nông sản đúng vụ và danh sách rau củ quả ngon nhất tháng này.',
    date: '02 Th4, 2024',
    views: '2.7K',
    image: require('../../assets/images/web/articles/article-nong-san-theo-mua.webp'),
  },
] as const;

export const FARM_STORIES = [
  {
    id: 'story-1',
    tag: 'VietGAP',
    title: 'Nông dân Đồng Tháp trồng xoài VietGAP bỏ túi tiền tỷ mỗi năm',
    moTa: 'Từ một nông dân truyền thống đến trang trại xoài đạt chuẩn VietGAP, câu chuyện làm giàu tử tế đầy cảm hứng.',
    date: '10 Th4, 2024',
    views: '3.2K',
    image: require('../../assets/images/web/stories/story-nong-dan-dong-thap-trong-xoai.jpg'),
  },
  {
    id: 'story-2',
    tag: 'Trang trại',
    title: 'Gia đình 10 người rời TP.HCM lên Đà Lạt mở trang trại',
    moTa: 'Thuê đồi trọc mở trang trại xanh giữa lòng Đà Lạt, mang đến những nông sản tươi mát an toàn tuyệt đối.',
    date: '08 Th4, 2024',
    views: '2.9K',
    image: require('../../assets/images/web/stories/story-trang-trai-xanh-da-lat.jpg'),
  },
  {
    id: 'story-3',
    tag: 'Chuyển đổi số',
    title: 'Nông sản Việt bắt nhịp chuyển đổi số và truy xuất nguồn gốc',
    moTa: 'Ổn định đầu ra nhờ công nghệ mã QR truy xuất - cầu nối đưa nông sản chất lượng cao đến gần người tiêu dùng.',
    date: '05 Th4, 2024',
    views: '4.1K',
    image: require('../../assets/images/web/stories/story-nong-san-bat-nhip-chuyen-doi-so.jpg'),
  },
] as const;

export const SERVICE_COMMITMENTS = [
  {
    // Web SERVICE_STRIP_ITEMS dùng icon `truck` — mobile tương đương car-outline.
    // Trước đây dùng airplane-outline gây lệch web.
    icon: 'car-outline' as const,
    title: 'Giao nhanh toàn quốc',
    desc: 'Từ 1-3 ngày, hàng tươi đến tận tay',
  },
  {
    icon: 'shield-checkmark-outline' as const,
    title: 'Truy xuất nguồn gốc',
    desc: 'Minh bạch từ lô đất đến bàn ăn',
  },
  {
    icon: 'headset-outline' as const,
    title: 'Hỗ trợ 24/7',
    desc: 'Tư vấn tận tình mọi lúc mọi nơi',
  },
  {
    icon: 'card-outline' as const,
    title: 'Thanh toán an toàn',
    desc: 'COD & VNPay bảo mật tối đa',
  },
] as const;
