export const MA_QUYEN = {
  PHAN_QUYEN_QUAN_LY: 'phan_quyen.quan_ly',
  SAN_PHAM_XEM: 'san_pham.xem',
  SAN_PHAM_TAO: 'san_pham.tao',
  DON_HANG_XU_LY: 'don_hang.xu_ly',
  TON_KHO_DIEU_CHINH: 'ton_kho.dieu_chinh',
  AUDIT_XEM: 'audit.xem',
  NHA_CUNG_CAP_XEM: 'nha_cung_cap.xem',
  NHA_CUNG_CAP_TAO: 'nha_cung_cap.tao',
  NHA_CUNG_CAP_SUA: 'nha_cung_cap.sua',
  NHA_CUNG_CAP_KHOA: 'nha_cung_cap.khoa',
  TRANG_TRAI_XEM: 'trang_trai.xem',
  TRANG_TRAI_TAO: 'trang_trai.tao',
  TRANG_TRAI_SUA: 'trang_trai.sua',
  TRANG_TRAI_KHOA: 'trang_trai.khoa',
  CHUNG_NHAN_XEM: 'chung_nhan.xem',
  CHUNG_NHAN_TAO: 'chung_nhan.tao',
  CHUNG_NHAN_SUA: 'chung_nhan.sua',
  CHUNG_NHAN_XAC_MINH: 'chung_nhan.xac_minh',
  MUA_VU_XEM: 'mua_vu.xem',
  MUA_VU_TAO: 'mua_vu.tao',
  MUA_VU_SUA: 'mua_vu.sua',
  NHAT_KY_CANH_TAC_XEM: 'nhat_ky_canh_tac.xem',
  NHAT_KY_CANH_TAC_TAO: 'nhat_ky_canh_tac.tao',
  NHAT_KY_CANH_TAC_SUA: 'nhat_ky_canh_tac.sua',
  THU_HOACH_XEM: 'thu_hoach.xem',
  THU_HOACH_TAO: 'thu_hoach.tao',
  THU_HOACH_SUA: 'thu_hoach.sua',
  LO_SAN_PHAM_XEM: 'lo_san_pham.xem',
  LO_SAN_PHAM_TAO: 'lo_san_pham.tao',
  LO_SAN_PHAM_SUA: 'lo_san_pham.sua',
  KIEM_DINH_CHAT_LUONG_XEM: 'kiem_dinh_chat_luong.xem',
  KIEM_DINH_CHAT_LUONG_TAO: 'kiem_dinh_chat_luong.tao',
} as const;

export const MA_VAI_TRO = {
  KHACH_HANG: 'KHACH_HANG',
  NHAN_VIEN: 'NHAN_VIEN',
  ADMIN: 'ADMIN',
} as const;
